/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'deigote' at '6/30/14 6:33 PM' with Gradle 1.9
 *
 * @author deigote, @date 6/30/14 6:33 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
