/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'deigote' at '6/30/14 6:33 PM' with Gradle 1.9
 *
 * @author deigote, @date 6/30/14 6:33 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
